import assert from "node:assert/strict";
import fs from "node:fs";
const root=new URL("../",import.meta.url);
const pkg=JSON.parse(fs.readFileSync(new URL("package.json",root),"utf8"));
const manifest=JSON.parse(fs.readFileSync(new URL("data/manifest.json",root),"utf8"));
const app=fs.readFileSync(new URL("app.js",root),"utf8");
const explore=fs.readFileSync(new URL("explore/app.js",root),"utf8");
const layout=fs.readFileSync(new URL("src/explore-layout.js",root),"utf8");
const css=fs.readFileSync(new URL("explore/styles.css",root),"utf8");
assert.equal(pkg.version,"1.2.44");
assert.equal(manifest.version,"1.2.44");
assert.equal(manifest.beta_version,"1.2.44");
assert.ok(app.includes("import('./explore/app.js?v=1.2.44')"));
assert.ok(app.includes("renderWelcome();"));
assert.ok(app.includes("onFindPath:()=>{ window.location.href='./?exploreReturn=1'; }"));
assert.ok(explore.includes("const VERSION = '1.2.44'"));
assert.ok(explore.includes("<g class=\"explore-edges\"></g><g class=\"explore-nodes\"></g>"));
assert.ok(explore.includes("g.addEventListener('click'"));
assert.ok(!explore.includes('g.innerHTML='));
assert.ok(explore.includes('edgesGroup.appendChild(line)'));
assert.ok(explore.includes('nodesGroup.appendChild(g)'));
assert.ok(explore.includes("type=node.id==='english'?'Your Home'"));
assert.ok(!explore.includes("'Root'"));
assert.ok(explore.includes("nodeRevealStart"));
assert.ok(explore.includes("edgeRevealStart"));
assert.ok(layout.includes("viewportScale"));
assert.ok(layout.includes("font=clamp(13.2*prominence*viewportScale"));
assert.ok(css.includes(".explore-edges"));
assert.ok(css.includes(".explore-nodes"));
assert.ok(css.includes("font-size:.88rem"));
assert.ok(css.includes("@media(max-width:700px)"));
console.log('v1.2.29 visual refinement checks passed');
