import fs from "node:fs";
import assert from "node:assert/strict";
const root=new URL("../",import.meta.url);
const pkg=JSON.parse(fs.readFileSync(new URL("package.json",root),"utf8"));
const manifest=JSON.parse(fs.readFileSync(new URL("data/manifest.json",root),"utf8"));
const explore=fs.readFileSync(new URL("explore/app.js",root),"utf8");
const css=fs.readFileSync(new URL("explore/styles.css",root),"utf8");
assert.equal(pkg.version,"1.3.0");
assert.equal(manifest.version,"1.3.0");
assert.equal(manifest.beta_version,"1.3.0");
assert.ok(!explore.includes("explore-close"));
assert.ok(!explore.includes("key==='Escape'"));
assert.ok(explore.includes("explore-path-btn"));
assert.ok(!css.includes(".explore-close"));
console.log("v1.2.29 Explore exit-point checks passed");
