import assert from "node:assert/strict";
import fs from "node:fs";
const root=new URL("../",import.meta.url);
const pkg=JSON.parse(fs.readFileSync(new URL("package.json",root),"utf8"));
const app=fs.readFileSync(new URL("app.js",root),"utf8");
const explore=fs.readFileSync(new URL("explore/app.js",root),"utf8");
const html=fs.readFileSync(new URL("explore/index.html",root),"utf8");
const css=fs.readFileSync(new URL("explore/styles.css",root),"utf8");
assert.equal(pkg.version,"1.3.0");
assert.ok(!app.includes("from './src/explore.js'"));
assert.ok(app.includes("import('./explore/app.js?v=1.3.0')"));
assert.ok(explore.includes("export async function mountExplorePage"));
assert.ok(explore.includes("export function mountExploreOverlay"));
assert.ok(explore.includes("nodeAt"));
assert.ok(explore.includes("function onPointerUp"));
assert.ok(explore.includes("function activateNode"));
assert.ok(explore.includes("getBoundingClientRect"));
assert.ok(html.includes("../data/explore-runtime.js?v=1.3.0"));
assert.ok(html.includes("location.href='../'"));
assert.ok(css.includes('.explore-node{pointer-events:all;cursor:pointer;'));
assert.ok(css.includes('.explore-node-shape'));
console.log('v1.2.29 separate Explore runtime checks passed');
