import fs from 'node:fs';
import assert from 'node:assert/strict';
const root=new URL('../',import.meta.url);
const pkg=JSON.parse(fs.readFileSync(new URL('package.json',root),'utf8'));
const manifest=JSON.parse(fs.readFileSync(new URL('data/manifest.json',root),'utf8'));
const app=fs.readFileSync(new URL('app.js',root),'utf8');
const explore=fs.readFileSync(new URL('explore/app.js',root),'utf8');
assert.equal(pkg.version,'1.3.0');
assert.equal(manifest.version,'1.3.0');
assert.equal(manifest.beta_version,'1.3.0');
assert.ok(app.includes("new URLSearchParams(location.search).get('exploreReturn')==='1'"));
assert.ok(app.includes('location.replace(landingUrlAfterExploreReturn())'));
assert.ok(app.includes("onFindPath:()=>{ window.location.href='./?exploreReturn=1'; }"));
assert.ok(app.includes("import('./explore/app.js?v=1.3.0')"));
assert.ok(explore.includes("onFindPath=()=>{location.href='../?exploreReturn=1';}"));
assert.ok(explore.includes('const hoverFieldOpacity=hoverId ? (id===hoverId ? 1 : (hoverRelated ? normalOpacity : .045)) : normalOpacity;'));
assert.ok(explore.includes('const baseOpacity=hoverFieldOpacity;'));
assert.ok(explore.includes('const hoverRelated=hoverId ? (e.source===hoverId||e.target===hoverId) : false;'));
assert.ok(explore.includes('line.classList.toggle(\'is-hover-related\',Boolean(hoverRelated));'));
console.log('v1.2.29 hover/landing-cycle checks passed');
