import fs from 'node:fs';
import assert from 'node:assert/strict';
const root=new URL('../',import.meta.url);
const pkg=JSON.parse(fs.readFileSync(new URL('package.json',root),'utf8'));
const manifest=JSON.parse(fs.readFileSync(new URL('data/manifest.json',root),'utf8'));
const app=fs.readFileSync(new URL('app.js',root),'utf8');
const css=fs.readFileSync(new URL('styles.css',root),'utf8');
const exploreCss=fs.readFileSync(new URL('explore/styles.css',root),'utf8');
const readme=fs.readFileSync(new URL('README.md',root),'utf8');
assert.equal(pkg.version,'1.2.32');
assert.equal(manifest.version,'1.2.32');
assert.equal(manifest.beta_version,'1.2.32');
assert.ok(app.includes('id="exploreLaunch"'));
assert.ok(app.includes('EXPLORE! English</span></button>'));
assert.ok(!app.includes('explore-launch-glint'));
assert.ok(css.includes('.explore-launch-btn{'));
assert.ok(css.includes('background:#805c31'));
assert.ok(css.includes('font:inherit;font-weight:700'));
assert.ok(!css.includes('explore-button-glint'));
assert.ok(!css.includes('conic-gradient'));
assert.ok(exploreCss.includes('.explore-path-btn{'));
assert.ok(exploreCss.includes('padding:8px 14px'));
assert.ok(exploreCss.includes('font-size:.82rem'));
assert.ok(readme.includes('## Pathfinder project history'));
assert.ok(readme.includes('### v1.0.4'));
assert.ok(readme.includes('### v1.2.6'));
assert.ok(readme.includes('### v1.2.11'));
assert.ok(readme.includes('### v1.2.18'));
assert.ok(readme.includes('### v1.2.29'));
console.log('v1.2.29 landing control / README refinement checks passed');
