import fs from "node:fs";
import assert from "node:assert/strict";
const root=new URL("../",import.meta.url);
const pkg=JSON.parse(fs.readFileSync(new URL("package.json",root),"utf8"));
const manifest=JSON.parse(fs.readFileSync(new URL("data/manifest.json",root),"utf8"));
const app=fs.readFileSync(new URL("app.js",root),"utf8");
const css=fs.readFileSync(new URL("styles.css",root),"utf8");
const explore=fs.readFileSync(new URL("explore/app.js",root),"utf8");
assert.equal(pkg.version,"1.2.43");
assert.equal(manifest.version,"1.2.43");
assert.equal(manifest.beta_version,"1.2.43");
assert.ok(app.includes("? 5000 : 30000"));
assert.ok(explore.includes("const PRODUCTION_IDLE_MS = 30000"));
assert.ok(app.includes('id="exploreLaunch"'));
assert.ok(app.includes("app.querySelector('#exploreLaunch').addEventListener('click',launchExplore)"));
assert.ok(app.includes("import('./explore/app.js?v=1.2.43')"));
assert.ok(css.includes('.explore-launch-btn{'));
assert.ok(css.includes('background:#805c31'));
assert.ok(!css.includes('explore-button-glint'));
assert.ok(!css.includes('conic-gradient'));
assert.ok(css.includes('@media (prefers-reduced-motion:reduce)'));
assert.ok(app.includes("Explore English could not load; Pathfinder continues normally."));
assert.ok(app.includes("location.href='./?exploreReturn=1'"));
console.log('v1.2.29 landing Explore button/timing checks passed');
