import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../',import.meta.url);
const pkg=JSON.parse(fs.readFileSync(new URL('package.json',root),'utf8'));
const manifest=JSON.parse(fs.readFileSync(new URL('data/manifest.json',root),'utf8'));
const graph=JSON.parse(fs.readFileSync(new URL('data/explore-english.graph.json',root),'utf8'));
const explore=fs.readFileSync(new URL('explore/app.js',root),'utf8');
const readme=fs.readFileSync(new URL('README.md',root),'utf8');
const audit=fs.readFileSync(new URL('docs/SEMANTIC_AUDIT.md',root),'utf8');
assert.equal(pkg.version,'1.2.43');
assert.equal(manifest.version,'1.2.43');
assert.equal(manifest.beta_version,'1.2.43');
assert.ok(graph.nodes.some(n=>n.id==='social_media' && n.type==='hub' && n.metadata?.category==='resource_community'));
for(const id of ['social_english_facebook','social_english_instagram','social_solas_facebook','social_solas_links','social_writing_center_instagram']) assert.ok(graph.nodes.some(n=>n.id===id));
assert.ok(explore.includes('if(id===hoverId) baseOpacity=1;'));
assert.ok(explore.includes('Math.max(normalOpacity,.74)-normalOpacity'));
assert.ok(explore.includes('const contextTarget=(hoverId&&id!==hoverId&&hoverRelated)?1:0;'));
assert.ok(explore.includes('edgeBase=hoverRelated?.48:(related?.10:.055)'));
assert.ok(audit.includes('Exact normalized-label rule'));
assert.ok(readme.includes('v1.2.27 social media and hover-context refinement'));
console.log('v1.2.29 Social Media and hover-context refinement checks passed');
