import fs from 'node:fs';
import assert from 'node:assert/strict';
const root=new URL('../',import.meta.url);
const pkg=JSON.parse(fs.readFileSync(new URL('package.json',root),'utf8'));
const manifest=JSON.parse(fs.readFileSync(new URL('data/manifest.json',root),'utf8'));
const app=fs.readFileSync(new URL('app.js',root),'utf8');
const explore=fs.readFileSync(new URL('explore/app.js',root),'utf8');
const css=fs.readFileSync(new URL('styles.css',root),'utf8');
const exploreCss=fs.readFileSync(new URL('explore/styles.css',root),'utf8');
const readme=fs.readFileSync(new URL('README.md',root),'utf8');
assert.equal(pkg.version,'1.2.29');
assert.equal(manifest.version,'1.2.29');
assert.equal(manifest.beta_version,'1.2.29');
assert.ok(app.includes('? 5000 : 30000'));
assert.ok(explore.includes('const PRODUCTION_IDLE_MS = 30000'));
assert.ok(explore.includes('const AUTOPLAY_HOLD_MS = 15000'));
assert.ok(explore.includes('/2000,0,1'));
assert.ok(explore.includes('Math.min(620,i*32)'));
assert.ok(explore.includes("seededHash(id+'::reveal')%700"));
assert.ok(!css.includes('.explore-launch-btn:hover,.explore-launch-btn:focus-visible'));
assert.ok(!css.includes('.explore-launch-btn:hover{'));
assert.ok(!exploreCss.includes('.explore-path-btn:hover,.explore-path-btn:focus-visible'));
assert.ok(readme.includes('### v1.2.29'));
assert.ok(readme.includes('30 seconds'));
console.log('v1.2.29 timing, motion, and button-state checks passed');
