import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
const root=new URL("../",import.meta.url);
const explore=fs.readFileSync(new URL("../explore/app.js",import.meta.url),"utf8");
const manifest=JSON.parse(fs.readFileSync(new URL("data/manifest.json",root),"utf8"));
const pkg=JSON.parse(fs.readFileSync(new URL("package.json",root),"utf8"));
assert.equal(pkg.version,'1.2.44');
assert.equal(manifest.version,'1.2.44');
assert.equal(manifest.beta_version,'1.2.44');
assert.ok(explore.includes("const VERSION = '1.2.44'"));
assert.ok(explore.includes("const GRAPH_URL = '../data/explore-english.graph.json?v=1.2.44'"));
assert.ok(explore.includes('function baseMotionDepth(id)'));
assert.ok(explore.includes('return id===hoverId ? 1 : baseMotionDepth(id);'));
assert.ok(explore.includes('Math.max(normalOpacity,.74)-normalOpacity'));
assert.ok(explore.includes('hoverContextProgress'));

assert.ok(explore.includes('function isHoverNeighborhood(id)'));
assert.ok(explore.includes("g.addEventListener('pointerenter'"));
assert.ok(explore.includes("g.addEventListener('click'"));
console.log('v1.2.29 hierarchical hover refinement tests passed');
