import assert from 'node:assert/strict';
import fs from 'node:fs';
import { createExploreGraph } from '../src/explore-graph.js';
const root=new URL('../',import.meta.url);
const pkg=JSON.parse(fs.readFileSync(new URL('package.json',root),'utf8'));
const manifest=JSON.parse(fs.readFileSync(new URL('data/manifest.json',root),'utf8'));
const explore=fs.readFileSync(new URL('explore/app.js',root),'utf8');
const motion=fs.readFileSync(new URL('src/explore-motion.js',root),'utf8');
assert.equal(pkg.version,'1.2.48');
assert.equal(manifest.version,'1.2.48');
assert.equal(manifest.beta_version,'1.2.48');
assert.ok(explore.includes('const motionState=new Map()'));
assert.ok(explore.includes('function motionDepth(id)'));
assert.ok(explore.includes('function stepMotion(ts)'));
assert.ok(explore.includes('function drawPoint(id,p,ts,nodeElapsed)'));
assert.ok(explore.includes('line.setAttribute(\'x1\',da.x.toFixed(2))'));
assert.ok(explore.includes('line.setAttribute(\'x2\',db.x.toFixed(2))'));
assert.ok(explore.includes('const settle=frozen?.90:.018'));
assert.ok(explore.includes('Courteous avoidance'));
assert.ok(explore.includes('Boundaries are steering fields, not walls'));
assert.ok(explore.includes("targetNode=e.target.closest?.('.explore-node')"));
assert.ok(explore.includes('m.oscX=0;m.oscY=0;'));
assert.ok(motion.includes('Math.min(88,width*.078)'));
assert.ok(motion.includes('Math.min(64,height*.064)'));
const graph=JSON.parse(fs.readFileSync(new URL('data/explore-english.graph.json',root),'utf8'));
const g=createExploreGraph(graph);
assert.equal(g.nodes.length,216);
assert.equal(graph.edges.length,595);
console.log('v1.2.29 depth-aware motion refinement checks passed');
