import assert from 'node:assert/strict';
import fs from 'node:fs';
const app=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');
const styles=fs.readFileSync(new URL('../styles.css',import.meta.url),'utf8');
const copy=JSON.parse(fs.readFileSync(new URL('../data/copy.json',import.meta.url),'utf8'));
const pkg=JSON.parse(fs.readFileSync(new URL('../package.json',import.meta.url),'utf8'));
assert.equal(pkg.version,'1.3.0');
assert.equal(copy.EXPLORATORY_KEY,'A FEW PATHS ARE OPENING UP.');
assert.ok(app.includes('spec.copy.profile_shape?.EXPLORATORY_KEY'));
assert.ok(app.includes('You chose the room where something is about to be published.'));
assert.ok(!app.includes('I’d stick around, too.'));
assert.ok(app.includes('Mystery solved.'));
assert.ok(app.includes("let nightMode = sessionStorage.getItem('pathfinderNightMode') === 'true';"));
assert.ok(app.includes('function applyNightMode()'));
assert.ok(app.includes('function toggleNightMode()'));
assert.ok(app.includes('id="nightModeToggle"'));
assert.ok(app.includes("document.body.classList.toggle('night-mode', nightMode)"));
assert.ok(styles.includes('body.night-mode'));
assert.ok(styles.includes('.night-mode-toggle'));
assert.ok(styles.includes('Presentation-only Night mode'));
assert.ok(app.includes('const navigateAt=Math.max(revealSecond, revealSecond+OUTBOUND_HOLD_MS);'));
assert.ok(app.includes('activateOutboundDestination(url,target,openedWindow);'));
assert.ok(styles.includes('.computing-screen .computing-dots{position:static'));
assert.ok(!styles.includes('.bonus-transition-dots{position:static'));
console.log('v1.2.x compatibility refinement tests passed');
