import fs from "node:fs";
import assert from "node:assert/strict";
const root=new URL("../",import.meta.url);
const pkg=JSON.parse(fs.readFileSync(new URL("package.json",root),"utf8"));
const manifest=JSON.parse(fs.readFileSync(new URL("data/manifest.json",root),"utf8"));
const explore=fs.readFileSync(new URL("explore/app.js",root),"utf8");
const readme=fs.readFileSync(new URL("README.md",root),"utf8");
assert.equal(pkg.version,"1.3.0");
assert.equal(manifest.version,"1.3.0");
assert.equal(manifest.beta_version,"1.3.0");
assert.ok(explore.includes("const VERSION = '1.3.0'"));
assert.ok(explore.includes("edgeRevealStart=burstStart+750"));
assert.ok(explore.includes("/2000,0,1"));
assert.ok(explore.includes("edgeElapsed-localDelay"));
assert.ok(readme.includes("v1.2.29 line-reveal timing refinement"));
console.log("v1.2.29 line-reveal timing checks passed");
