import assert from 'node:assert/strict';
import fs from 'node:fs';
import crypto from 'node:crypto';
const read=p=>fs.readFileSync(new URL('../'+p,import.meta.url),'utf8');
const graph=JSON.parse(read('data/explore-english.graph.json'));
const app=read('explore/app.js');
const css=read('explore/styles.css');
const pkg=JSON.parse(read('package.json'));
const manifest=JSON.parse(read('data/manifest.json'));
assert.equal(pkg.version,'1.2.48');
assert.equal(manifest.version,'1.2.48');
assert.equal(manifest.beta_version,'1.2.48');
assert.ok(app.includes("const VERSION = '1.2.48'"));
assert.ok(app.includes('data-shortcut="programs"'));
assert.ok(!app.includes('data-shortcut="expertise"'));
assert.ok(app.includes("const programPrimaryIds=['ba_english','graduate_studies','minors','certificates']"));
assert.ok(app.includes("positions=layoutExploreNodes({nodes:visibleNodes,centerId:focusId,width:w,height:h,rootMode:focusId==='english'});"));
assert.ok(app.includes('positionShortcuts();'));
assert.ok(app.includes('syncShortcutGeometry(ts);'));
assert.ok(app.includes("const displayLabel=node.id==='programs'?'Programs':node.label;"));
assert.ok(css.includes('.explore-shortcut-label.is-visible'));
assert.ok(css.includes('.explore-shortcut.is-excited::before'));
assert.ok(!css.includes('scale(1.05)'));
assert.ok(!css.includes('scale(1.16)'));
assert.ok(css.includes('width:120px;height:48px'));
const edge=(a,b)=>graph.edges.some(e=>(e.source===a&&e.target===b)||(e.source===b&&e.target===a));
assert.ok(edge('programs','ba_english'));
assert.ok(edge('ba_english','conc_language'));
assert.ok(edge('conc_language','ug_tesol'));
const hashes={motion:'fe4a545ff5d5d0e19d1206d11e40fc5f818bf7657d60de3b6e92eb1af3ea5321',layout:'975fe7b5d935e91ae6dbfe377aebbf3abc8e0585d0fadd662b284586b53d0dfc',environment:'e617fee8f16017c95c603b320181c4000290a156a637999f849768d3715e538c'};
for(const [k,f] of Object.entries({motion:'src/explore-motion.js',layout:'src/explore-layout.js',environment:'src/explore-environment.js'})) assert.equal(crypto.createHash('sha256').update(fs.readFileSync(new URL('../'+f,import.meta.url))).digest('hex'),hashes[k],f+' must remain frozen');
console.log('v1.2.48 launch cluster and shared Programs convention checks passed.');
