import assert from 'node:assert/strict';
import fs from 'node:fs';
const app=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');
const styles=fs.readFileSync(new URL('../styles.css',import.meta.url),'utf8');
const copy=JSON.parse(fs.readFileSync(new URL('../data/copy.json',import.meta.url),'utf8'));
const questions=JSON.parse(fs.readFileSync(new URL('../data/questions.json',import.meta.url),'utf8'));
const pkg=JSON.parse(fs.readFileSync(new URL('../package.json',import.meta.url),'utf8'));
const manifest=JSON.parse(fs.readFileSync(new URL('../data/manifest.json',import.meta.url),'utf8'));
assert.equal(pkg.version,'1.2.7');
assert.equal(manifest.version,'1.2.7');
assert.equal(manifest.beta_version,'1.2.7');
assert.ok(app.includes('exploratoryGuidance'));
assert.ok(app.includes('Your answers crossed several connected areas of English, so think of these as starting points—places to explore rather than limits on where your interests can take you.'));
assert.ok(app.includes('Start with your strongest curricular pathway, then take a look at the other graduate pathways that fit.'));
assert.ok(!app.includes("You chose the room where something is about to be published. There’s something exciting about seeing ideas take their final shape—and maybe helping them get there. I’d stick around, too."));
assert.ok(app.includes('Mystery solved.'));
assert.ok(app.includes("document.documentElement.classList.toggle('night-mode', nightMode)"));
assert.ok(app.includes('id="nightModeToggle"'));
assert.ok(app.includes('class="welcome-actions"'));
assert.ok(styles.includes('html.night-mode,body.night-mode'));
assert.ok(styles.includes('.welcome-actions .night-mode-toggle{margin-left:auto}'));
assert.ok(styles.includes('html,body{min-height:100%;background:#f6f1e8}'));
assert.ok(styles.includes('min-height:100svh'));
assert.ok(!app.includes('bonus-transition-dots'));
assert.ok(!styles.includes('.bonus-transition-dots{'));
assert.ok(!styles.includes('bottom:clamp(28px,6vh,54px)'));
assert.ok(styles.includes('.computing-screen .computing-dots{position:static'));
assert.ok(styles.includes('.interest-info::before'));
assert.ok(styles.includes('body.night-mode .bonus-transition-card{background:#302925'));
assert.ok(styles.includes('body.night-mode .personalization-note p{color:#e1d8cf}'));
assert.ok(app.includes('font-size:clamp(1.75rem,5.1vw,3.8rem)'));
assert.ok(app.includes('name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"'));
assert.ok(app.includes('@media (max-width:700px){.handoff{width:calc(100vw - 24px);max-width:19ch;padding:22px 12px;font-size:clamp(1.65rem,8.4vw,2.8rem);line-height:1.04}}'));
assert.ok(app.includes("const holdingBg=nightMode ? '#24201d' : '#f6f1e8';"));
assert.ok(app.includes("const holdingFg=nightMode ? '#f4eee6' : '#1e1b18';"));
assert.ok(app.includes("color-scheme:${nightMode?'dark':'light'}"));
assert.ok(!app.includes('font-size:1.8rem'));
const outboundFn=app.split('function renderOutboundTransition',2)[1]?.split('function renderBonusTransition',1)[0] || '';
assert.ok(!outboundFn.includes("overlay.classList.add('is-fading-out')"));
assert.ok(styles.includes('width:.9rem;height:.9rem'));
assert.ok(styles.includes('.interest-info{width:1.25rem;height:1.25rem;'));
assert.ok(app.includes('function activateOutboundDestination(url, target, openedWindow=null)'));
assert.ok(app.includes("openedWindow=window.open('', '_blank')"));
assert.ok(app.includes('activateOutboundDestination(url,target,openedWindow);'));
const outboundBody=app.split('function renderOutboundTransition',2)[1]?.split('function renderBonusTransition',1)[0] || '';
assert.ok(outboundBody.includes('activateOutboundDestination(url,target,openedWindow);'));
assert.ok(!outboundBody.includes("overlay.classList.add('is-fading-out')"));
assert.equal(questions.find(q=>q.id==='PER01').options.find(o=>o.id==='PER01_LAB').signals?.length ?? 0, 0);
const w02=questions.find(q=>q.id==='W02');
const expected={W02_BOOKS:{LIT:2,INQ:1},W02_ACCENTS:{LANG:2,CUL:1},W02_STORIES:{CRA:2},W02_MIND:{LANG:2,CUL:1,INQ:1},W02_MENU:{PRO:2,RHE:1}};
for (const [id,vec] of Object.entries(expected)) { const opt=w02.options.find(o=>o.id===id); assert.ok(opt,`missing ${id}`); assert.deepEqual(opt.signals,vec); }
assert.ok(app.includes('resultHandoffSeen[kind]=true;'));
console.log('v1.2.7 refinement tests passed');
