import assert from 'node:assert/strict';
import fs from 'node:fs';
const graph=JSON.parse(fs.readFileSync(new URL('../data/explore-english.graph.json',import.meta.url),'utf8'));
const app=fs.readFileSync(new URL('../explore/app.js',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../explore/styles.css',import.meta.url),'utf8');
const byId=new Map(graph.nodes.map(n=>[n.id,n]));
const edge=(a,b)=>graph.edges.some(e=>(e.source===a&&e.target===b)||(e.source===b&&e.target===a));
assert.equal(byId.get('solas_cebuano_onomatopoeia')?.label,'Onomatopoeias');
assert.ok(!byId.has('topic_education'));
assert.ok(edge('kyle_simonsen','topic_sports_writing'));
assert.ok(edge('study_abroad','london_suffrage'));
assert.ok(edge('linden_review','english_internships'));
assert.ok(edge('english','faculty'));
assert.equal(byId.get('topic_tesol')?.center_blurb,'Explore TESOL through faculty, courses, research, and related opportunities.');
assert.ok(app.includes('data-shortcut="opportunities"'));
assert.ok(app.includes('data-shortcut="programs"'));
assert.ok(!app.includes('data-shortcut="expertise"'));
assert.ok(app.includes('data-shortcut="social_media"'));
assert.ok(app.includes('EXPLORE!</div><div class="explore-shortcut-preview-title">'));
assert.ok(css.includes('.explore-shortcut.is-excited::before'));
assert.ok(css.includes('.explore-shortcut-label.is-visible'));
assert.ok(css.includes('filter:blur(4px)'));
assert.ok(app.includes('positionShortcuts();'));
assert.ok(app.includes('syncShortcutGeometry(ts);'));
assert.ok(app.includes('class="link-arrow"'));
console.log('v1.2.44 refinement tests passed.');
