import fs from "node:fs";
import assert from "node:assert/strict";
import { classifyExploreEnvironment } from "../src/explore-environment.js";
import { getExploreMotionProfile, getMobileOscillation } from "../src/explore-motion.js";
const root=new URL("../",import.meta.url);
const explore=fs.readFileSync(new URL("explore/app.js",root),"utf8");
const exploreCss=fs.readFileSync(new URL("explore/styles.css",root),"utf8");
const app=fs.readFileSync(new URL("app.js",root),"utf8");
const pkg=JSON.parse(fs.readFileSync(new URL("package.json",root),"utf8"));
const manifest=JSON.parse(fs.readFileSync(new URL("data/manifest.json",root),"utf8"));
assert.equal(pkg.version,"1.2.30");
assert.equal(manifest.version,"1.2.30");
assert.equal(manifest.beta_version,"1.2.30");
assert.ok(explore.includes("const VERSION = '1.2.30'"));

const iphone=classifyExploreEnvironment({width:390,coarse:true,hoverNone:true,touchPoints:5,userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1',platform:'iPhone'});
assert.equal(iphone.compactTouch,true);
assert.equal(iphone.mobileSafari,true);
const desktop=classifyExploreEnvironment({width:1440,coarse:false,hoverNone:false,touchPoints:0,userAgent:'Mozilla/5.0 AppleWebKit/537.36 Chrome/140 Safari/537.36',platform:'MacIntel'});
assert.equal(desktop.compactTouch,false);
assert.equal(desktop.mobileSafari,false);

const phoneMotion=getExploreMotionProfile({width:390,height:844,coarse:true});
assert.equal(phoneMotion.mobileProfile,true);
assert.equal(phoneMotion.motionScale,3.2);
assert.ok(phoneMotion.maxX>=44&&phoneMotion.maxY>=32);
const osc=getMobileOscillation({t:12.5,phase:1.7,depth:.7,isFocus:false,mobileProfile:true,frozen:false});
assert.ok(Math.abs(osc.x)+Math.abs(osc.y)>.2,'mobile oscillation must produce visible non-zero displacement');
assert.deepEqual(getMobileOscillation({t:12.5,phase:1.7,depth:.7,isFocus:false,mobileProfile:false,frozen:false}),{x:0,y:0});

assert.ok(explore.includes("await ensureExploreStyles()"));
assert.ok(explore.includes("edgesGroup.setAttribute('transform',worldTransform)"));
assert.ok(explore.includes("nodesGroup.setAttribute('transform',worldTransform)"));
assert.ok(!explore.includes("svg.style.transform=`translate("));
assert.ok(explore.includes("const directTouchActivation=p.nodeId&&!p.moved&&p.pointerType!=='mouse'"));
assert.ok(explore.includes("view.setPointerCapture?.(e.pointerId)"));
assert.ok(explore.includes("now-lastRafPaint>360"));
assert.ok(explore.includes("window.addEventListener('pageshow',wakeAnimation)"));
assert.ok(explore.includes("Find your way through English."));
assert.ok(explore.includes("overlay.dataset.mobileSafari"));
assert.ok(app.includes("const controller=await mod.mountExploreOverlay"));
assert.ok(app.includes("Find your way through English."));
assert.ok(exploreCss.includes('-webkit-touch-callout:none'));
assert.ok(exploreCss.includes('backdrop-filter:none'));
assert.ok(exploreCss.includes('.explore-entry{'));
console.log("v1.2.30 mobile Safari renderer and environment-detection checks passed");
