import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../',import.meta.url);
const read=p=>fs.readFileSync(new URL(p,root),'utf8');
const app=read('explore/app.js');
const css=read('explore/styles.css');
const pkg=JSON.parse(read('package.json'));
assert.equal(pkg.version,'1.3.0');
assert.ok(app.includes('let lastPointerActivitySignal=0;'),'pointer activity throttle exists');
assert.ok(app.includes("if(e.pointerType==='mouse'||e.pointerType==='pen')"),'pointer movement activity covers mouse/pen');
assert.ok(app.includes('lastPointerActivitySignal>=120'),'pointer movement signal is throttled');
assert.ok(app.includes('lastPointerActivitySignal=now;'),'pointer movement updates activity clock');
assert.ok(app.includes('noteActivity();'),'pointer movement resets autoplay inactivity lifecycle');
assert.ok(app.includes("overlay?.classList.add('pathfinder-prompt-active');"),'transition owns Pathfinder glow state');
assert.ok(app.includes("overlay?.classList.remove('pathfinder-prompt-active');"),'Pathfinder glow is cleared after transition');
assert.ok(css.includes('.pathfinder-prompt-active .explore-path-btn'),'Find My Path glow targets the existing button');
assert.ok(css.includes('@keyframes pathfinderPromptGlow'),'Find My Path glow is animated');
const hold=Number(app.match(/AUTOPLAY_HOLD_MS = (\d+);/)?.[1]);
const transition=Number(app.match(/AUTOPLAY_TRANSITION_MS = (\d+);/)?.[1]);
assert.equal(hold+transition,25000,'autoplay arrivals remain 25 seconds apart');
console.log('PASS: v1.3.0 pointer movement resets autoplay and transition callout targets Pathfinder');
