import assert from "node:assert/strict";
import fs from "node:fs";
const root=new URL("../",import.meta.url);
const pkg=JSON.parse(fs.readFileSync(new URL("package.json",root),"utf8"));
const explore=fs.readFileSync(new URL("explore/app.js",root),"utf8");
const layout=fs.readFileSync(new URL("src/explore-layout.js",root),"utf8");
const styles=fs.readFileSync(new URL("styles.css",root),"utf8");
assert.equal(pkg.version,"1.2.31");
assert.ok(explore.includes("new ResizeObserver"));
assert.ok(explore.includes("layoutExploreNodes"));
assert.ok(explore.includes("visibleNodes"));
assert.ok(!explore.includes("scale(${fontScale"));
assert.ok(layout.includes("collision") || layout.includes("penalty"));
assert.ok(layout.includes("mobile?12"));
assert.ok(layout.includes("presentationFor"));
assert.ok(fs.readFileSync(new URL("explore/styles.css",root),"utf8").includes(".explore-hit"));
assert.ok(explore.includes("AUTOPLAY_HOLD_MS = 15000"));
assert.ok(explore.includes("AUTOPLAY_HOME_REST_MS = 3400"));
console.log("v1.2.29 responsive Explore renderer checks passed");
